services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    ports:
      - 8000:8000
      - 5002:5002
    tty: true

  jupyter:
    image: jupyter/base-notebook
    volumes:
      - ..:/workspace
    ports:
      - 8888:8888
    environment:
      - JUPYTER_ENABLE_LAB=yes
