version: '3.8'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - "8000:8000"
      - "8888:8888"
    environment:
      - PYTHONUNBUFFERED=1
