name: Deploy Flask Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create and activate venv
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Build React and copy to backend
        run: |
          source venv/bin/activate
          cd frontend
          npm install
          npm run build
          cd ..
          mkdir -p app/static app/templates
          cp -r frontend/build/static/* app/static/
          cp frontend/build/index.html app/templates/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Zappa Package
        run: |
          source venv/bin/activate
          zappa package production
          mv package.zip flask-api.zip

      - name: Deploy or Update with Zappa
        run: |
          source venv/bin/activate
          (zappa status production 2>&1 | grep -q 'not deployed' || zappa status production 2>&1 | grep -q 'No Lambda') && \
            zappa deploy production || \
            zappa update production
